spring:
  application:
    name: StudentInformationSystem
---
spring:
  config:
    active:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testDb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
